---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.3.4
  kernelspec:
    display_name: R
    language: R
    name: ir
---

```{r}
install.packages('PoSI', repos='http://cloud.r-project.org')
```

```{r}
X = matrix(rnorm(5000), 250, 20)
library(PoSI)
```

```{r}
?PoSI
```

```{r}
data(Boston, package="MASS")
set.seed(1)
.Random.seed <- 1:626
UL.Boston <- PoSI(Boston[,-14])
summary(UL.Boston)
    ##     K.PoSI K.Bonferroni K.Scheffe
    ## 95%  3.593        4.904     4.729
    ## 99%  4.072        5.211     5.262
```

```{r}
library(MASS)
data(Boston)
```

```{r}
?Boston
```

```{r}
library(glmnet)
Y = as.numeric(Boston[,14])
X = as.matrix(Boston[,-14])
random_order = sample(1:506, 506, replace=FALSE)
train = random_order[1:250]
test = random_order[251:506]
cvG = cv.glmnet(X[train,], Y[train])
plot(cvG)
```

```{r}
G = glmnet(X[train,], Y[train])
beta_train = coef(G, s=cvG$lambda.1se)[-1]
selected_train = which(beta_train != 0)
selected_train

```

```{r}
selected_conf = confint(lm(Y ~ X[,selected_train], subset=test))
selected_conf
```

$\approxleq$

```{r}
L_selected = selected_conf[,2] - selected_conf[,1]
```

```{r}
cvG_all = cv.glmnet(X, Y)
G_all = glmnet(X, Y)
beta_all = coef(G, s=cvG_all$lambda.1se)[-1]
selected_all = which(beta_all != 0)
selected_all
```

```{r}
posi_conf = confint(lm(Y ~ X[,selected_all]), level=1 - 2 * pnorm(-3.593))
```

```{r}
L_posi = posi_conf[,2] - posi_conf[,1]
```

```{r}
data.frame(selected=L_selected, posi=L_posi)
```

```{r}

```
